version: '3.1'

services:
    mysql:
        image: mariadb
        restart: always
        container_name: mariadb
        environment:
            MARIADB_ROOT_PASSWORD: root
            MARIADB_DATABASE: web3
            MARIADB_USER: web3
            MARIADB_PASSWORD: web3
        ports:
            - 3306:3306
        volumes:
            - ./mysql/data:/var/lib/mysql
